# Environment file for GRiMP Notebooks
name: greenlandMapping
#
channels:
  - conda-forge
dependencies:
  - python=3.10
  - blosc
  - curl
  - dask
  - datashader
  - fsspec
  - gdal
  - geoviews  
  - geopandas
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  # As of November 22, panel 1.3.2 and param 2.0 not working. So for now pin
  - panel<1
  - param<2
  - pip
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - stackstac
  - tiledb
  - pip:
    - git+https://github.com/fastice/grimpfunc.git@master
    - git+https://github.com/fastice/grimpqgis.git@master
    - git+https://github.com/fastice/nisardev.git@main
    - git+https://github.com/developmentseed/rio-stac@main
    
